# Generated by Django 2.2.3 on 2019-07-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinyurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tinyurl',
            name='short_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
