# Generated by Django 2.2.3 on 2019-07-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20190725_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tinyurl',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='tinyurl',
            name='short_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
