# Generated by Django 2.2.3 on 2019-08-01 17:31

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20190728_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.check_com, shortner.validators.validate_url]),
        ),
    ]
